### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by slivingston** [StanfordASL/TrafficWeavingCVAE#1]
Can you provide a license for the code and data? (Preferably, open source.)

**Comment by slivingston** [comment]
perhaps move [TrafficWeavingPlanner/LICENSE.md](https://github.com/StanfordASL/TrafficWeavingCVAE/blob/9e53aaddcbcf8bffa9ceb0940bdaa3f777b27db5/TrafficWeavingPlanner/LICENSE.md) to the root directory, and declare it in the root README ?

**Comment by schmrlng** [comment]
Both this repository and the associated dataset `.zip` now contain a `LICENSE.md`.
